### ISSUE TITLE
Template group names on other language

### ISSUE THREAD

**Issue by Leny1337** [ATofighi/TemplateEditor#3]
Hi. I'm using Polish language and there is issue with group names.
![editingtemplates](https://cloud.githubusercontent.com/assets/8152038/7403893/6188fa60-eedb-11e4-9831-aa68ea571d7a.jpg)

"Szablony" means "Templates"

**Comment by ATofighi** [comment]
Hi,
You should use MyBB 1.8.4+

**Comment by Leny1337** [comment]
How to fix this on 1.8.3? I don't want to update MyBB, becouse I've many files edited right now and don't have enough time to "recopy" it on new files from 1.8.4.

Thanks in advance

**Comment by ATofighi** [comment]
in your language files:
`inc/languages/yourlang/admin/styles_templates.lang.php`,
find: 

```
Szablony
```

change to:

```
{1} Szablony
```

**Comment by Leny1337** [comment]
Thank you :)
